### ISSUE TITLE
Start on home category

### ISSUE THREAD

**Issue by Commenter25** [peterfajdiga/FastDraw#17]
I keep a home category which is meant to be the apps I use most frequently, and then I switch categories for my more uncommon apps. Ideally, it would always start on this category when I go home.

This might not be intuitive to some, so it should probably be off by default; or if you want to avoid adding another option, have it only happen after the screen has turned off, or after a timeout.

**Comment by peterfajdiga** [comment]
It's a good idea. The home button is already set up to move to the first category, when already in the launcher. Maybe the first step would be to make it switch to the first category more often - for example every time when opening the launcher, except when using the back button from an app.

**Comment by Commenter25** [comment]
I would like to suggest basing it around the home category instead of the first category. My setup is 5 categories, with home in the middle. This was the most logical and efficient ordering I could think of, keeping every app only two swipes away. This is perhaps a niche setup, but I believe the most intuitive solution, and I doubt I'm the only one who would want to do this.

![An image of my categories. In order: Games, Social, Home, Work, Misc](https://github.com/peterfajdiga/FastDraw/assets/35016761/80b6a0ee-2445-4690-b729-cbd80c522ebf)

**Comment by ljoonal** [comment]
I've been thinking that it'd be nice to start from the middle of my categories instead of from the leftmost one, so that I don't need to scroll so much to the right to access the last category

My developer brain is just telling me that a very easy and "goodEnoughTM" solution would be to just have a preference for the default category index, and open that (or default to 0 if the specified one does not exist). That does sound like bad UX, but maybe that could work as an initial solution, and later on if there's interest, the UI portions of that preference can be made better (meanwhile I figure that storing the index should be fine even then)?

**Comment by peterfajdiga** [comment]
It should now always (except when going back from another app) switch to the home or the first category (not the middle one, as I guess that would be slightly less intuitive, even if it would be more ergonomic).
