### ISSUE TITLE
better layout 

### ISSUE THREAD

**Issue by xi7** [peterfajdiga/FastDraw#20]
new tab app by default on bottom because is too bad one hand icons on top and all people will use like favorites.
-keep only gridview on top.

**Comment by Commenter25** [comment]
I may be misunderstanding what you're asking for, but the "Place tabs on bottom" setting sounds like what you want. It's in the General section of the preferences.

**Comment by xi7** [comment]
if tabs on top show apps on bottom.
if tabs on bottom show apps on bottom.

**Comment by peterfajdiga** [comment]
This would be nice when using tabs on bottom, because it would remove the hole between the apps and the tabs. I've been playing with this back when I was implementing widget support, but there's actually no nice way to do this, so I've dropped it.

The problem is that the app icons area has a constant height (but part of it is hidden when scrolling up to reveal the widget) so that scrolling works nicely with category switching. If the icons were populated from the bottom, they would not be visible when scrolling up to reveal the widget (they would be below the screen).

When/if I implement https://github.com/peterfajdiga/FastDraw/issues/4#issuecomment-1879742131, this will also be solved, but for now it's unsolveable.
