### ISSUE TITLE
Open Apps List Sometimes Won't Open

### ISSUE THREAD

**Issue by softwarepagan** [peterfajdiga/FastDraw#34]
I just recently installed FastDraw and I'm loving it, but I noticed that sometimes the recent/open apps list sometimes stops working with FastDraw enabled as the default homescreen. I am on Android 14 (LineageOS 21) and using FastDraw 2.1.2

Thank you.

**Comment by peterfajdiga** [comment]
Hi, thanks for the report! What does it mean that the app switcher stops working? Does it crash, does it just not open? Does this happen with any other custom launchers?

**Comment by softwarepagan** [comment]
When it crashes it simply refuses to open anymore until I go into the settings of the stock launcher (trebuchet) and force stop it and clear its cache. This occurs with all custom launchers.

**Comment by peterfajdiga** [comment]
Thanks for the info. It doesn't sound like this is something that can be fixed in the launcher. :/

**Comment by xxxserxxx** [comment]
I don't know if I'm seeing exactly the same issue as OP, but I have FastDraw set as my launcher and sometimes when I open the home screen FastDraw is frozen. I don't think it's hung, because I can tap the screen and it'll launch a random app (whatever icon was in that place, but never what was drawn on the screen). I can leave and return and it stays frozen until I go into global settings and force stop the app, after which it has a brief convulsion and then works normally until the next time.

I have not identified what triggers this, but it happens about once or twice a week on average, I'd guess.

v2.2.1 from f-droid, on a Samsung Flip phone, Android 15.

**Comment by peterfajdiga** [comment]
@xxxserxxx That is a different issue and thank you for reporting it! Please open a separate issue for it. And please include the following details: When the app freezes, is it only the apps list that's frozen? The rest of the app still works, for example, you can longpress and drag an icon, and you can change tabs (but the new category is not displayed)?
